### ISSUE TITLE
Repair model issues

### ISSUE THREAD

**Issue by spritezs** [stacs-cp/AutoIG#10]
This is the repair file in Essence format (github doesn't allow me to add it with the extension .essence)
[repair.txt](https://github.com/user-attachments/files/17634435/repair.txt)

This is one is the eprime version which resides in the detailed output folder:
[repair.txt](https://github.com/user-attachments/files/17634570/repair.txt)

After calling run.sh the first error is encountered when this is called:

_conjure solve repair.essence  ./detailed-output//repair-1.param  -o  ./detailed-output/  --use-existing-model repair.eprime   --solver-options "-timelimit 120 -varorder domoverwdeg -randomiseorder -randomseed 1 "  --copy-solutions=off_

The error text is:

_Savile Row: ./detailed-output/repair.eprime ./detailed-output//repair-1.param
Error: Missing values for parameters: usage_card_min, usage_card_delta_

Next I will attach the repair-1.param file, which actually contains both of these variables (again in txt format since github doesn't allow the extension .param)
[repair-1.txt](https://github.com/user-attachments/files/17634641/repair-1.txt)

The program doesn't crash here though. But it crashes when trying to run the first race:
_Error: == irace == Not enough configurations (1) for a race (minSurvival=5)_

The error might be due to the fact that conjure doesn't finish repairing any of the parameter files (if I understood this correctly),
but when running savilerow independently:

 _savilerow -run-solver ./detailed-output/repair.eprime ./detailed-output/repair-1.param_

we do get the solution file:
[repair-1.param.txt](https://github.com/user-attachments/files/17634762/repair-1.param.txt)

**Comment by ndangtt** [comment]
Hi @spritezs,

Assuming that you're using the car-sequencing generator model provided here: https://github.com/stacs-cp/AutoIG/blob/dev/data/models/car-sequencing/generator.essence, I think there are a number of issues in in the repair model and the example repair param file:

**repair model:**

1. `usage_card_min` and `usage_card_delta` are defined twice.
2. There are 11 parameters of the generator to be repaired, but there are only 7 `find` statements in the repair model. 

**repair.param**
There are only 11 parameters of the generator to be repaired, but there are 15 values provided in this example. Some of the `letting` statements don't correspond to any `given` in the repair model (and the generator model).

**Comment by spritezs** [comment]
[repair.txt](https://github.com/user-attachments/files/17706670/repair.txt)

Complete and revised repair model. Now car graded runs like a new Mustang. Running it doesn't break anywhere else so I think that's us done with graded instances :)) @ndangtt @vincepick

**Comment by ndangtt** [comment]
@spritezs: congrats on getting the issue closed!
