### ISSUE TITLE
Savile row issue when running vessel-loading

### ISSUE THREAD

**Issue by spritezs** [stacs-cp/AutoIG#14]
When I ran vessel-loading I ran into this problem. The program calls conjure but breaks when running savile row. I don't understand this error and none of my files are 2000 lines long so I don't know where to look for a solution:

```
Calling conjure
2024-11-16 17:43:57: conjure solve ./problem.essence ./detailed-output/inst-13-1489266180.param -o ./detailed-output --use-existing-models=problem.eprime --savilerow-options "-timelimit 1 " --solver-options "-t 1000 --rnd-seed 1489266180 " --solver=chuffed
2024-11-16 17:43:59: Error:
    Savile Row stdout: Created output file for domain filtering ./detailed-output/problem-inst-13-1489266180.eprime-minion
Created output file ./detailed-output/problem-inst-13-1489266180.eprime-param.fzn
Sub-process exited with error code:134 and error message:
[WARNING: the --time-out flag has recently been changed.The time-out is now provided in milliseconds instead of seconds, Error: Registry: Constraint all_different_int not found in line no. 2097]
Solver exited with error code:134 and message:
[WARNING: the --time-out flag has recently been changed.The time-out is now provided in milliseconds instead of seconds, Error: Registry: Constraint all_different_int not found in line no. 2097]
Created information file ./detailed-output/problem-inst-13-1489266180.eprime-info

    Savile Row stderr: 
    Savile Row exit-code: 0
Using existing models.
Savile Row: ./detailed-output/problem.eprime ./detailed-output/inst-13-1489266180.param
Running minion for domain filtering.
Running solver: chuffed
```

It is weird that it ran smoothly for a dozen variations or so but broke here.

**Comment by ozgurakgun** [comment]
If you email me the input files for this I can investigate. The error is coming from chuffed, it could be the solver's fault or our translation's. Also we should make sure we are using latest SR.

**Comment by pwn1** [comment]
This is a mismatch between the name of the constraint in Savile Row, and the name in the Chuffed flatzinc parser.  Sometimes they change the names in Chuffed and I don't notice until the next time I update the Chuffed binary that is bundled with SR. 

This problem should not be happening if you're using the latest release of SR with its bundled chuffed binary -- in that case, I definitely want to know about it.   I also want to know if you're using the latest version on the main branch of SR with the latest Chuffed release.

**Comment by pwn1** [comment]
However SR should have been producing fzn_all_different_int since March 2023 at the latest, so perhaps something else is going on here.  Was the Chuffed flag definitely used when generating that .fzn file?

**Comment by spritezs** [comment]
Ashamed to admit the problem was due to the unupdated version of SR. After changing the installation script and updating the SR version from 1.9.1 to 1.10.1 it worked perfectly. Thank you all for the help (would never have thought about the SR version)!!! Thank you for your time @ozgurakgun @pwn1 !

**Comment by ozgurakgun** [comment]
No need to be ashamed! Good to hear it now works.
