### ISSUE TITLE
KeyError: 'score' bug when running AutoIG in a container

### ISSUE THREAD

**Issue by vincepick** [stacs-cp/AutoIG#2]
I have created two new containers that automate more of the setup for AutoIG when run through Docker. One approach clones the AutoIG repo each time the container is built, the other uses a Docker volume to allow changes to AutoIG to persist on the machine the container is being run on. 

For the purpose of debugging the containerization, the first approach will be used, and the instructions are below. 

Every time run.sh is run, there is an error thrown and the program crashes. 

<img width="1158" alt="Screenshot 2024-08-04 at 12 25 01 AM" src="https://github.com/user-attachments/assets/e8754327-cd70-424e-b582-871c5017e794">

# Commands to build and run docker container
docker build --platform linux/amd64 -t conjure_clone_image .

docker run -it --name <my-interactive-conjure-app> conjure_clone_image /bin/bash

# Commands to run after container is built 

. bin/set-path.sh

AUTOIG=$(pwd)

mkdir -p experiments/macc-graded/

cd experiments/macc-graded/

python $AUTOIG/scripts/setup.py --generatorModel $AUTOIG/data/models/macc/generator-small.essence --problemModel $AUTOIG/data/models/macc/problem.mzn --instanceSetting graded --minSolverTime 0 --maxSolverTime 5 --solver chuffed --solverFlags="-f" --maxEvaluations 180 --genSolverTimeLimit 5

bash run.sh

# Dockerfile used: 

### Conjure: https://github.com/conjure-cp/conjure/blob/main/

Dockerfile
FROM ghcr.io/conjure-cp/conjure:main

### Update the package list
RUN apt-get update

### Install necessary packages with frontend=noninteractive to avoid interactive prompts
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
    bash \
    sudo \
    wget \
    curl \
    gnupg \
    software-properties-common \
    unzip

### Install necessary python packages
RUN sudo apt-get install -y python3-pip
RUN apt install python3-pandas -y
RUN apt install python3-numpy -y

### Ensure 'python' command points to Python 3
RUN sudo apt install python-is-python3

### Install R base package for irace
RUN sudo apt-get install r-base -y

### Install Git
RUN sudo apt-get install git-all -y

### Set working directory to root
WORKDIR /

### Clone the AutoIG repository from GitHub
RUN git clone https://github.com/stacs-cp/AutoIG.git

### Move conjure into the AUtoIG bin directory
RUN mv conjure AutoIG/bin

### Set the working directory
WORKDIR /AutoIG

### Run installation scripts for tools used by AutoIG
RUN bash bin/install-savilerow.sh   # Install Savile Row
RUN bash bin/install-mininzinc.sh   # Install MiniZinc
RUN bash bin/install-irace.sh       # Install irace
RUN bash bin/install-runsolver.sh   # Install RunSolver
RUN bash bin/install-ortools.sh     # Install OR-Tools
RUN bash bin/install-yuck.sh        # Install Yuck
RUN bash bin/install-picat.sh       # Install Picat

**Comment by ndangtt** [comment]
I think the errors are now fixed. The conjure docker image already installed minizinc and chuffed and they clashes with AutoIG's own installation of those softwares.

The fix includes two things:
- Latest commits on AutoIG repo.
- Adding the following commands into Dockerfile:
```
rm /root/.local/bin/minizinc
rm /root/.local/bin/fzn-chuffed
rm /root/.local/bin/fzn-cp-sat
rm -rf /root/.local/bin/share
```

Could you please give it a try and see if it works for you? Thanks!

I've also created a `dev` branch and add the Dockerfile into that. We can use this branch for future development from now on.

**Comment by vincepick** [comment]
Thank you so much for having a look, and I am glad to know that you found the cause of the errors. I made a few small changes to the Docker file, on the dev branch which fixed some of the syntax in the file. However, when I tried to run the additional rm commands either in the file or inside the container once it had been created, they seemed to work correctly but I unfortunately still got the same error as before. Did you use any different Docker build or run commands when it worked for you? I created a new DEV_README.md file which contained all of the exact commands I used and in what sequence, please let me know if any of my process differed from yours at all and I would be happy to experiment more. 

<img width="1323" alt="Screenshot 2024-08-12 at 1 15 15 PM" src="https://github.com/user-attachments/assets/97a4781a-f649-4a2d-b229-171d0ef7dabb">

# Contents of the README...
## Docker Build And Run Commands

docker build --platform linux/amd64 -t conjure_clone_image .

docker run -it --name <my-interactive-conjure-app> conjure_clone_image /bin/bash

## Commands To Run Inside Docker Container For Quick Start Example

. bin/set-path.sh

AUTOIG=$(pwd)

mkdir -p experiments/macc-graded/

cd experiments/macc-graded/

python $AUTOIG/scripts/setup.py --generatorModel $AUTOIG/data/models/macc/generator-small.essence --problemModel $AUTOIG/data/models/macc/problem.mzn --instanceSetting graded --minSolverTime 0 --maxSolverTime 5 --solver chuffed --solverFlags="-f" --maxEvaluations 180 --genSolverTimeLimit 5

## To Run The Generated Bash Script

bash run.sh



Thank you,
Vincent

**Comment by vincepick** [comment]
Fully functional, changed the platform from `linux/amd64` to `linux/amd64/v2` in the docker run command. Attached the successful output as a file and a screenshot to confirm the output is correct. 

<img width="1263" alt="Screenshot 2024-08-12 at 3 31 33 PM" src="https://github.com/user-attachments/assets/29804879-b305-4fb1-992e-22b3809415aa">

[runshSuccessfulOutput.txt](https://github.com/user-attachments/files/16592522/runshSuccessfulOutput.txt)
